export const REQUEST_LIST_REPOSITORIES_START = 'REQUEST_LIST_REPOSITORIES_START';
export const REQUEST_LIST_REPOSITORIES_SUCCESS = 'REQUEST_LIST_REPOSITORIES_SUCCESS';
export const REQUEST_LIST_REPOSITORIES_FAIL = 'REQUEST_LIST_REPOSITORIES_FAIL'; 